version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Started Pre-Build stage of Demo front end on `date`
      - npm install
      - npm audit fix
      - npm install -g @angular/cli
  build:
    commands:
      - echo Invalidating CloudFront Cache
      - aws cloudfront create-invalidation --distribution-id E18NZX2E9LGAKS --paths "/*"
      - echo Build stage started
      - ng build --prod
      - aws s3 sync ./dist/my-personal-menu/ s3://joeys.mymobile.menu --acl 'public-read' --delete
  post_build:
    commands:
      - echo Deployment completed on `date`
# artifacts:
#   files:
    # - demo-site.zip